Move functions to jack_client_patching from pypatcher
noiseorchestra/jacktrip_pypatcher pull request #34
Opened 2020-10-04 07:35 UTC by sandreae

2020-10-04 10:07 UTC, madwort commented on jacktrip_pypatcher.py
> +    autopatch(jcp, jackClient, dry_run, jacktrip_clients)
does this mean we need to update the tests as well? Ideally we'd make the tests meaningful, and then we could run them in CI, and that would catch this for us...

2020-10-04 10:16 UTC, madwort requested changes
a good improvement, but tests need updating to match

2020-10-04 10:18 UTC, madwort commented on jack_client_patching.py
> +            map(lambda x: x.name.split(":")[0], jackClient.get_ports(".*receive_1")))
we can use `self.jackClient` instead of `jackClient` here

2020-10-04 10:19 UTC, madwort commented on jacktrip_pypatcher.py
> +    jacktrip_clients = jcp.get_current_clients(jackClient, dry_run)
if we use `self.jackClient` above, this can become 
`    jacktrip_clients = jcp.get_current_clients(dry_run)`

2020-10-04 10:37 UTC, madwort commented on jacktrip_pypatcher.py
> +    autopatch(jcp, jackClient, dry_run, jacktrip_clients)
oh, and actually maybe we can just pass `jcp` and use `jcp.jackClient`? haven't checked but...

2020-10-04 15:00 UTC, sandreae commented on jacktrip_pypatcher.py
> +    autopatch(jcp, jackClient, dry_run, jacktrip_clients)
yep, will update the tests :+1:

2020-10-09 20:35 UTC, sandreae commented
Closing because we've now implemented this in some other PRs.

2020-10-09 20:35 UTC, closed without merging