Merge two ladspa test files
noiseorchestra/jacktrip_pypatcher pull request #45
Opened 2020-10-05 22:20 UTC by madwort

* another typo!

2020-10-06 20:01 UTC, sandreae reviewed
Looks good, however I came across this on the ladspa_client PR https://github.com/noiseorchestra/jacktrip_pypatcher/pull/45 and thought this file was an accidental duplicate of `ltest_adspa_plugins` so removed it here https://github.com/noiseorchestra/jacktrip_pypatcher/pull/42/commits/6003aa249c393c01c0a35c6079aba90be80c9dd3

Is there a good order to merge these two PR in?

2020-10-07 11:50 UTC, sandreae submitted a review, later dismissed
Probably best to merge this first as the other PR is a bit more in-depth :+1:

2020-10-07 12:04 UTC, madwort commented
yep - I think the other PR should only have changes to tests that are directly to do with the new code - any tidying up / moving tests should be done in a seperate PR?

2020-10-07 12:04 UTC, madwort commented
but actually - which of these two names is correct?

2020-10-07 12:05 UTC, madwort commented
the other file is `ladspa_plugins.py` so I think this should be `test_ladspa_plugins.py` -> I'll update the PR when I get a min

2020-10-07 12:09 UTC, sandreae commented
> the other file is `ladspa_plugins.py` so I think this should be `test_ladspa_plugins.py` -> I'll update the PR when I get a min

Yeh, I agree. Actually, I don't know where the other `ladspa_plugin.py` file came from, I thought it was a mistake when I saw it....

2020-10-07 16:56 UTC, madwort commented
ok, looks good now?

2020-10-07 18:59 UTC, sandreae requested changes
I think this section of code is an error, right?

2020-10-07 19:02 UTC, madwort commented
which one sorry?

2020-10-07 19:04 UTC, sandreae reviewed
> which one sorry?

Sorry, see below.... (the last function in `test_ladspa_plugins.py`

2020-10-07 19:04 UTC, sandreae commented on test_ladspa_plugins.py
> +    ]
This whole function doesn't make sense, right?

2020-10-07 21:14 UTC, madwort commented on test_ladspa_plugins.py
> +    ]
ah, this is from before `ladspa` got converted to an object, so it's got the wrong function signature. Will revise this PR for the current codebase.

2020-10-08 09:53 UTC, madwort commented
will re-do in the new context

2020-10-08 09:53 UTC, closed without merging